apiVersion: v1
kind: Service
metadata:
  name: ingress-service-devops
  namespace:  haproxy-controller-devops
  labels:
    app: haproxy-ingress
spec:
  type: NodePort
  selector:
    app: haproxy-ingress
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32456
  - name: https
    port: 443
    targetPort: 443
    nodePort: 32567
  - name: stat
    port: 1024
    protocol: TCP
    targetPort: 1024
    nodePort: 32678
  #ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
   # - port: 80
      #targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      #nodePort: 30007
  
